# Generated by Django 6.0.4 on 2026-05-06 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pirate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('sot_rat', models.TextField()),
                ('last_sync', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.PositiveIntegerField()),
                ('fish_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_manager', to='fish.fishvariant')),
                ('pirate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_manager', to='pirate.pirate')),
            ],
            options={
                'unique_together': {('pirate', 'fish_variant')},
            },
        ),
    ]
