# Generated by Django 6.0.4 on 2026-05-04 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sot_campaign_key', models.CharField(max_length=20, unique=True)),
                ('sot_index', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FishVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('limit', models.PositiveSmallIntegerField()),
                ('sot_index', models.PositiveSmallIntegerField()),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_manager', to='fish.fish')),
            ],
            options={
                'unique_together': {('fish', 'sot_index')},
            },
        ),
    ]
