name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Check out code
        uses: actions/checkout@v6
      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          push: true
          context: backend
          tags: getpastthemonkey/sea-of-fishing:backend
          platforms: amd64,arm64
  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Check out code
        uses: actions/checkout@v6
      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          push: true
          context: frontend
          tags: getpastthemonkey/sea-of-fishing:frontend
          platforms: amd64,arm64
  notify:
    name: Notify Watchtower
    runs-on: ubuntu-latest
    needs:
      - build_backend
      - build_frontend
    steps:
      - name: Notify Watchtower
        run: |
          curl -fsSL -H "${{ secrets.WATCHTOWER_AUTH_HEADER }}" -X "POST" https://${{ vars.WATCHTOWER_HOST }}/watchtower/v1/update
